apiVersion: v1
kind: Service
metadata:
  name: {{ include "call-n-cache.fullname" . }}
  labels:
    {{- include "call-n-cache.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.metricsPort }}
      targetPort: metrics
      protocol: TCP
      name: metrics
    {{- if .Values.jsonExporter.enabled }}
    - port: {{ .Values.jsonExporter.port }}
      targetPort: json-metrics
      protocol: TCP
      name: json-metrics
    {{- end }}
  selector:
    {{- include "call-n-cache.selectorLabels" . | nindent 4 }}
